//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookInfo
    {
        public int ISBN { get; set; }
        public string BookTitle { get; set; }
        public string IsBookAvaliable { get; set; }
        public string BookEdition { get; set; }
        public string BookAuthor { get; set; }
    }
}
